import { useState, useEffect } from 'react';
import { useCMS } from '../../contexts/CMSContext';
import { 
  Sparkles, 
  Bot, 
  Play, 
  RotateCcw, 
  Copy, 
  ThumbsUp, 
  ThumbsDown,
  Save,
  X
} from 'lucide-react';

interface AIContentCreatorProps {
  onClose: () => void;
  onInsertContent: (content: string) => void;
}

export default function AIContentCreator({ onClose, onInsertContent }: AIContentCreatorProps) {
  const { aiProviders, aiModels, fetchAIModels, createAIJob } = useCMS();
  const [selectedProvider, setSelectedProvider] = useState<number | ''>('');
  const [selectedModel, setSelectedModel] = useState<number | ''>('');
  const [prompt, setPrompt] = useState('');
  const [generatedContent, setGeneratedContent] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationHistory, setGenerationHistory] = useState<any[]>([]);
  const [activeTab, setActiveTab] = useState<'create' | 'history'>('create');

  // Load models when provider is selected
  useEffect(() => {
    if (selectedProvider) {
      fetchAIModels(Number(selectedProvider));
    }
  }, [selectedProvider, fetchAIModels]);

  const handleGenerateContent = async () => {
    if (!selectedProvider || !selectedModel || !prompt) return;
    
    setIsGenerating(true);
    
    try {
      const job = await createAIJob({
        provider_id: Number(selectedProvider),
        model_id: Number(selectedModel),
        prompt,
        content: '',
        metadata: JSON.stringify({
          task_type: 'content_generation',
          created_at: new Date().toISOString()
        })
      });
      
      if (job) {
        // Simulate content generation (in a real app, this would be handled by a background process)
        setTimeout(() => {
          const mockContent = `This is AI-generated content based on your prompt: "${prompt}". 
          
In a real implementation, this would be replaced with actual content generated by the selected AI model (${aiModels.find(m => m.id === selectedModel)?.name}).`;
          
          setGeneratedContent(mockContent);
          setIsGenerating(false);
          
          // Add to history
          setGenerationHistory(prev => [{
            id: Date.now(),
            provider: aiProviders.find(p => p.id === selectedProvider)?.name,
            model: aiModels.find(m => m.id === selectedModel)?.name,
            prompt,
            content: mockContent,
            timestamp: new Date().toISOString()
          }, ...prev]);
        }, 2000);
      }
    } catch (error) {
      console.error('Failed to generate content:', error);
      setIsGenerating(false);
    }
  };

  const handleInsertContent = () => {
    onInsertContent(generatedContent);
    onClose();
  };

  const handleSaveToHistory = () => {
    // In a real implementation, this would save to the database
    setGenerationHistory(prev => [{
      id: Date.now(),
      provider: aiProviders.find(p => p.id === selectedProvider)?.name,
      model: aiModels.find(m => m.id === selectedModel)?.name,
      prompt,
      content: generatedContent,
      timestamp: new Date().toISOString()
    }, ...prev]);
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-xl w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200">
          <div className="flex items-center">
            <Sparkles className="w-6 h-6 text-[#2957c3] mr-3" />
            <h2 className="text-2xl font-bold text-gray-900">AI Content Creator</h2>
          </div>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-gray-700"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="border-b border-gray-200">
          <nav className="flex space-x-8 px-6">
            <button
              onClick={() => setActiveTab('create')}
              className={`py-4 px-1 border-b-2 font-medium text-sm ${
                activeTab === 'create'
                  ? 'border-[#2957c3] text-[#2957c3]'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              Create Content
            </button>
            <button
              onClick={() => setActiveTab('history')}
              className={`py-4 px-1 border-b-2 font-medium text-sm ${
                activeTab === 'history'
                  ? 'border-[#2957c3] text-[#2957c3]'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              History
            </button>
          </nav>
        </div>

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto p-6">
          {activeTab === 'create' && (
            <div className="space-y-6">
              {/* Provider and Model Selection */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    AI Provider
                  </label>
                  <select
                    value={selectedProvider}
                    onChange={(e) => setSelectedProvider(e.target.value as any)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-[#2957c3]"
                  >
                    <option value="">Select a provider</option>
                    {aiProviders.filter(p => p.enabled).map((provider) => (
                      <option key={provider.id} value={provider.id}>
                        {provider.name}
                      </option>
                    ))}
                  </select>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    AI Model
                  </label>
                  <select
                    value={selectedModel}
                    onChange={(e) => setSelectedModel(e.target.value as any)}
                    disabled={!selectedProvider}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-[#2957c3]"
                  >
                    <option value="">Select a model</option>
                    {aiModels.map((model) => (
                      <option key={model.id} value={model.id}>
                        {model.name}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              {/* Prompt Input */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Content Prompt
                </label>
                <textarea
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  rows={4}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-[#2957c3]"
                  placeholder="Describe the content you want to generate..."
                />
                <p className="mt-1 text-sm text-gray-500">
                  Be specific about the type of content, tone, and any key points you want to include.
                </p>
              </div>

              {/* Generate Button */}
              <div className="flex justify-center">
                <button
                  onClick={handleGenerateContent}
                  disabled={!selectedProvider || !selectedModel || !prompt || isGenerating}
                  className={`flex items-center px-6 py-3 rounded-lg font-medium ${
                    !selectedProvider || !selectedModel || !prompt || isGenerating
                      ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
                      : 'bg-[#2957c3] text-white hover:bg-blue-700'
                  }`}
                >
                  {isGenerating ? (
                    <>
                      <RotateCcw className="w-5 h-5 mr-2 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-5 h-5 mr-2" />
                      Generate Content
                    </>
                  )}
                </button>
              </div>

              {/* Generated Content */}
              {generatedContent && (
                <div className="border border-gray-200 rounded-lg">
                  <div className="flex items-center justify-between p-4 border-b border-gray-200">
                    <h3 className="font-medium text-gray-900">Generated Content</h3>
                    <div className="flex space-x-2">
                      <button
                        onClick={handleSaveToHistory}
                        className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded"
                        title="Save to history"
                      >
                        <Save className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => navigator.clipboard.writeText(generatedContent)}
                        className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded"
                        title="Copy to clipboard"
                      >
                        <Copy className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                  <div className="p-4 bg-gray-50">
                    <div className="prose max-w-none">
                      <p className="whitespace-pre-wrap">{generatedContent}</p>
                    </div>
                  </div>
                  <div className="p-4 border-t border-gray-200 bg-gray-50">
                    <div className="flex justify-end space-x-3">
                      <button
                        onClick={onClose}
                        className="px-4 py-2 text-gray-700 hover:text-gray-900 font-medium rounded-lg"
                      >
                        Cancel
                      </button>
                      <button
                        onClick={handleInsertContent}
                        className="bg-[#2957c3] text-white px-4 py-2 rounded-lg font-medium hover:bg-blue-700"
                      >
                        Insert Content
                      </button>
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}

          {activeTab === 'history' && (
            <div className="space-y-4">
              {generationHistory.length === 0 ? (
                <div className="text-center py-12">
                  <Bot className="w-12 h-12 text-gray-300 mx-auto mb-4" />
                  <h3 className="text-lg font-medium text-gray-900 mb-1">No generation history</h3>
                  <p className="text-gray-500">Generated content will appear here</p>
                </div>
              ) : (
                <div className="space-y-4">
                  {generationHistory.map((item) => (
                    <div key={item.id} className="border border-gray-200 rounded-lg">
                      <div className="p-4 border-b border-gray-200">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center">
                            <Bot className="w-5 h-5 text-[#2957c3] mr-2" />
                            <span className="font-medium text-gray-900">{item.provider}</span>
                            <span className="mx-2 text-gray-300">•</span>
                            <span className="text-gray-600">{item.model}</span>
                          </div>
                          <span className="text-sm text-gray-500">
                            {new Date(item.timestamp).toLocaleString()}
                          </span>
                        </div>
                        <p className="mt-2 text-sm text-gray-600">"{item.prompt}"</p>
                      </div>
                      <div className="p-4 bg-gray-50">
                        <div className="prose max-w-none">
                          <p className="whitespace-pre-wrap text-sm">{item.content}</p>
                        </div>
                      </div>
                      <div className="p-4 border-t border-gray-200 bg-gray-50">
                        <div className="flex justify-end space-x-2">
                          <button
                            onClick={() => navigator.clipboard.writeText(item.content)}
                            className="flex items-center px-3 py-1.5 text-sm text-gray-600 hover:text-gray-900 hover:bg-gray-200 rounded"
                          >
                            <Copy className="w-4 h-4 mr-1" />
                            Copy
                          </button>
                          <button
                            onClick={() => {
                              setGeneratedContent(item.content);
                              setActiveTab('create');
                            }}
                            className="flex items-center px-3 py-1.5 text-sm bg-[#2957c3] text-white rounded hover:bg-blue-700"
                          >
                            <RotateCcw className="w-4 h-4 mr-1" />
                            Regenerate
                          </button>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>

        {/* Footer */}
        {activeTab === 'create' && !generatedContent && (
          <div className="p-6 border-t border-gray-200 bg-gray-50">
            <div className="flex justify-end space-x-3">
              <button
                onClick={onClose}
                className="px-4 py-2 text-gray-700 hover:text-gray-900 font-medium rounded-lg"
              >
                Cancel
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}